
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Nov 18 09:42:07 PST 2022
//----------------------------------------------------

package Project;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESIDENCIALES = 8;
  public static final int CONDOMINIO = 9;
  public static final int STR_CONST = 5;
  public static final int EOF = 0;
  public static final int DIST = 4;
  public static final int DOT = 2;
  public static final int CARRETERA = 7;
  public static final int error = 1;
  public static final int COMMA = 3;
  public static final int KMS = 6;
}

