
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Oct 04 20:54:47 PDT 2022
//----------------------------------------------------

package Project;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 4;
  public static final int COMMA = 3;
  public static final int WORD = 5;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final int DOT = 2;
}

